### PR TITLE
Add support for color, panel and table

### PR DESCRIPTION
**Pull request by erykwarren**

### CODE REVIEW

**Comment by kylefarris** [comment]
Thanks for the pull request Eryk! These look like some great additions! I'm going to check it out, verify everything is still working, and let you know if there's anything you need to fix before the pull is accepted.

**Comment by kylefarris** [comment]
Cool, everything looks great. I'll merge the pull request and update the module in NPM.

**Comment by kylefarris** [comment]
NPM is updated. New version is now 1.5.1

**Comment by erykwarren** [comment]
Thanks for the quick review, Kyle! :100:

**Pull request merged**
